apiVersion: {{ .Values.status_service.status_apiVersion_service }}
kind: Service
metadata:
  name: {{ .Values.status_service.status_service_name }}
spec:
  selector:
    app: {{ .Values.status_deployment.status_deployment_name }}
  ports:
    - protocol: {{ .Values.status_deployment.status_protocol }}
      port: {{ .Values.status_deployment.status_port }}
      targetPort: {{ .Values.status_service.container_port }}
  type: {{ .Values.status_deployment.status_type }}